version: '2'
services:
    personalblog-app:
        image: personalblog
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://personalblog-mysql:3306/personalblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=personalblog-elasticsearch:9300
        ports:
            - 8080:8080
    personalblog-mysql:
        extends:
            file: mysql.yml
            service: personalblog-mysql
    personalblog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: personalblog-elasticsearch
